### ISSUE TITLE
Lista de Ideas Descartadas

### ISSUE THREAD

**Issue by craciunescu** [ubiqcomp/capacity#1]
Tenemos que hacer una lista de ideas de años pasados que no sean válidas. Preferiblemente en formato Markdown.

**Comment by ZainAzhar** [comment]
primer comentario

**Comment by HernandezIgnacio** [comment]
Poner un contador led para monitorizar el número de personas dentro del recinto.

**Comment by HernandezIgnacio** [comment]
Sistema de guiado hasta el local sin el aforo máximo completado más cercano.
