### ISSUE TITLE
Presentación PowerPoint

### ISSUE THREAD

**Issue by RobertPetrisor** [ubiqcomp/capacity#11]
Emplearemos mediante este issue para poder elaborar una vez hecho el resto de issues correspondientes a los diferentes apartados del cual se compone la PECL1, la presentación formal del proyecto a implementar.

**Comment by craciunescu** [comment]
Tal vez haya que poner esto en pausa y priorizar otros issues. Lo pongo en blocked.

**Comment by craciunescu** [comment]
It's time. Te recomiendo que uses canva.com. Te hace unas presentaciones de la hostia.
