### ISSUE TITLE
Targets and scope of the selected project

### ISSUE THREAD

**Issue by HernandezIgnacio** [ubiqcomp/capacity#2]
In this issue we will introduce all the targets we need to complete before finishing the assignment.

## Model
- [x] Build a structure to allocate the mechanism.
- [x] Detection of a person when he enters or leaves the place.
- [x] Create a counter of the people inside of the place.
- [ ] Indicate through LEDs, outside the place so people can check it's capacity without entering, the following states: 
  - [ ] Maximum capacity **not reached** (Ex. Green LED).
  - [ ] Maximum capacity **reached** (Ex. Yellow LED).
  - [ ] Maximum capacity **exceeded** (Ex. Red LED).
- [ ] In case of exceeding the maximum capacity, an special signal will be transmitted to activate several advises in the other components of the system

## Data base
- [ ] Create a server to allocate our database, so we can access it from any place in any moment we need.
- [ ] Design the database logical structure.
- [x] Generate a series of test places with static **invented** data to verify the correct server functioning
- [x] Connect this DB with our model to make sure the people flow will modify the DB data.

## Application
- [x] Connect the application to the DB to access the data from the application.
- [x] Display a list of the managed places and their information.
- [x] Filtering the list depending on its state (Ex. Only display full places)

**Comment by craciunescu** [comment]
Perfecto! ¿Qué te parece si creamos una lista de características contra la que validad aquello que creemos? Considéralo como un ```checklist``` para asegurarnos de que todo lo que queremos hacer lo hemos conseguido.

Te podrías poner tú con ello @HernandezIgnacio ?

**Comment by HernandezIgnacio** [comment]
Sí! Yo me encargo.

**Comment by craciunescu** [comment]
De lujo. No te olvides asignarte a la tarea en las opciones de la derecha y moverla a la columna de "In Progress" en la tabla de kanban.

![image](https://user-images.githubusercontent.com/25935100/97730116-bad6e800-1ad3-11eb-99eb-90ab8d6fc598.png)

**Comment by HernandezIgnacio** [comment]
## Maqueta
- [ ] Estructura que sirva para alojar el mecanismo.
- [ ] Detección de cuando una persona entra o sale del local.
- [ ] Conteo del número de personas dentro del local.
- [ ] Indicador por medio de LEDs para los siguientes estados del local: 
  - [ ] Aforo máximo **no alcanzado** (Ej. LED verde).
  - [ ] Aforo máximo **alcanzado** (Ej. LED amarillo).
  - [ ] Aforo máximo **superado** (Ej. LED rojo).

## Base de datos
- [ ] Diseñar la estructura lógica necesaria para la gestión de los locales.
- [ ] Generar una serie de locales de prueba con datos estáticos *inventados* que sirvan para comprobar el correcto funcionamiento del sistema.
- [ ] Conectar esta base de datos con nuestra maqueta para que el flujo de *personas* a través de él, modifique los datos en la BD.

## Aplicación
- [ ] Conectar la aplicación con la BD para acceder desde ella a la información.
- [ ] Mostrar la lista de los locales gestionados por nuestro sistema y su información.
- [ ] Poder filtrar la lista en función de su estado (Ej. Mostrar unicamente los locales llenos).

**Comment by craciunescu** [comment]
Tal vez la forma de indicar los estados del lugar sea un poco rudimentaria. Los LEDs desde luego son informativos, pero cómo de informativos serían si el dispositivo está puesto al lado de una puerta y simplemente no hay alguien al lado todo le rato mirando su color.

Me atrevería a decir que un simple sistema de alertas o incluso una aplicación extremadamente simple que tenga un contador podría ser mucho más efectiva.

---

También nos haría falta un servidor, dado que si queremos tener una base de datos, habrá que tener un mecanismo que pueda __procesar__ esa información.

---

No me queda del todo claro a qué te refieres con  __"Design the necessary logical structure for the place management."__

---

Te adjunto una imagen de una estructura de proyecto del año pasado para que te hagas una idea de qué cosas tendríamos que comprobar. Sé que no es 100% relevante a este issue, pero te puede ayudar.

![Screenshot 2020-11-18 at 17 34 05](https://user-images.githubusercontent.com/25935100/99558843-6df47c00-29c4-11eb-9980-5032d664ad99.png)

**Comment by craciunescu** [comment]
@HernandezIgnacio hay una parte en el #12 que tiene que ver con scope of the selected project. Tal vez crear una sección conjunta que tenga en cuenta las dos sea una buena idea, qué te parece?
