### ISSUE TITLE
Análisis del problema

### ISSUE THREAD

**Issue by HernandezIgnacio** [ubiqcomp/capacity#5]
Necesitamos diseñar un sistema **inteligente** que lleve a cabo el control del aforo de diferentes locales.
El sistema deberá recibir el flujo de entradas y salidas del local, llevar a cabo su cuenta y guardar estos datos en una BD, la cual también habrá que diseñar.
A su vez esta BD deberá estar conectada a una aplicación que permita acceder fácilmente a la información registrada.
Los objetivos de este proyecto están recogidos en el issue  [Objetivos y alcance del proyecto](#2).

**Comment by craciunescu** [comment]
Sin darme cuenta te he robado el issue y lo he hecho ya para la introducción. Lo enlazo con el (pull request)[#12] que hay abierto y hago que se cierre el issue automáticamente si se aprueba el request. Te voy a poner como revisor.
