### ISSUE TITLE
Planificación temporal, plan de desarrollo

### ISSUE THREAD

**Issue by RobertPetrisor** [ubiqcomp/capacity#7]
En esta sección, destacaremos los siguientes apartados a analizar:
-	Riesgos: incluiremos y describiremos aquellos riesgos fundamentales que nos impidan avanzar en nuestra etapa de desarrollo en cualquier momento.
-	Plan de contingencias: se abarcará los planes de respaldo, para ello se encargará de crear una imagen de marca fiable para dar prestigio a dicho empresa; planes de emergencia, teniendo en cuenta los riesgos, mencionados anteriormente, deberemos de asentar la competencia con el resto de los socios del mercado, como causa principal, para que de esta manera podemos diferenciarnos con un producto único y exclusivo ; y, por último, los planes de recuperación, que es la vía por el cual, demostraremos que nuestro servicio se diferenciará al cliente del resto del mercado.

**Comment by RobertPetrisor** [comment]
https://github.com/ubiqcomp/capacity/issues/7#issue-733545527

**Comment by craciunescu** [comment]
Este issue es demasiado complejo para ser un solo issue por su cuenta. Cada parte tendría que ser independientemente un issue. Lo voy a transformar.
